workflow:
  gen_data: false
  train: true
  checkpoint: true
dataset:
  sample_size: 51200
  sample_num: 6553600
  data_folder: ./data
  sample_sub_dir:
    - 10
    - 256
    - 256
  write_threads: 8
reader:
  batch_size: 10240
  read_threads: 8
  prefetch_size: 2
  shuffle: none
  seed: rand
  transfer_size: 51200
train:
  steps: 16
  interval: 100
checkpoint:
  checkpoint_folder: ./checkpoints
  checkpoint_size: 53687091200 # 50GB
  write_transfer_size: 104857600 # 100M
  read_transfer_size: 104857600 # 100M
  checkpoint_type: sync
  checkpoint_interval: 20
  checkpoint_layers: 5
  read_threads: 8
output:
  folder: ./kwai
