workflow:
  gen_data: false
  train: true
  checkpoint: false
dataset:
  sample_size: 524288
  sample_num: 24
  data_folder: ./data
  sample_sub_dir:
    - 2
    - 3
  write_threads: 4
reader:
  batch_size: 8
  read_threads: 4
  prefetch_size: 0
  shuffle: none
  seed: rand
  transfer_size: 524288
train:
  steps: 10
  interval: 0.1
checkpoint:
  checkpoint_folder: ./checkpoints
  checkpoint_size: 409600
  write_transfer_size: 262144
  read_transfer_size: 262144
  checkpoint_type: sync
  checkpoint_interval: 5
  checkpoint_layers: 1
  read_threads: 4
output:
  folder: ./result