workflow:
  gen_data: false
  train: true
  checkpoint: false
  gen_sample: false
dataset:
  sample_size: 65536
  sample_num: 24
  data_folder: ./data
  sample_sub_dir:
    - 2
    - 3
  write_threads: 4
reader:
  batch_size: 8
  read_threads: 4
  prefetch_size: 0
  shuffle: none
  seed: rand
  transfer_size: 65536
train:
  epochs: 10
checkpoint:
  checkpoint_folder: ./checkpoints
  checkpoint_size: 409600
  write_transfer_size: 262144
